### Importing libraries

```{r, message=F, warning=F}
library(tidyverse)
library(lubridate)
library(read.gt3x)
library(PhysicalActivity)
```

```{r}
temp <- df_1[10000:10100,]

#temp$time <- as.POSIXct(temp$time, format = "%Y-%m-%d %H:%M:%OS")

#temp$time <- force_tz(temp$time, tzone = "Europe/Berlin")

start_time <- as.POSIXct("2024-10-10 06:00:00.000")
end_time <- as.POSIXct("2024-10-10 06:45:00.000")

rest_1 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(rest_1$X)
mean(rest_1$Y)
mean(rest_1$Z)

start_time <- as.POSIXct("2024-10-10 20:45:00.000")
end_time <- as.POSIXct("2024-10-11 08:00:00.000")

rest_2 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(rest_2$X)
mean(rest_2$Y)
mean(rest_2$Z)

start_time <- as.POSIXct("2024-10-11 22:30:00.000")
end_time <- as.POSIXct("2024-10-12 09:45:00.000")

rest_3 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(rest_3$X)
mean(rest_3$Y)
mean(rest_3$Z)

#Now move on to walking

start_time <- as.POSIXct("2024-10-10 08:22:00.000")
end_time <- as.POSIXct("2024-10-10 08:28:00.000")

walk_1 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(walk_1$X)
mean(walk_1$Y)
mean(walk_1$Z)

start_time <- as.POSIXct("2024-10-10 09:37:00.000")
end_time <- as.POSIXct("2024-10-10 09:43:00.000")

walk_2 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(walk_2$X)
mean(walk_2$Y)
mean(walk_2$Z)

start_time <- as.POSIXct("2024-10-10 14:20:00.000")
end_time <- as.POSIXct("2024-10-10 14:34:00.000")

walk_3 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(walk_3$X)
mean(walk_3$Y)
mean(walk_3$Z)

start_time <- as.POSIXct("2024-10-14 12:54:00.000")
end_time <- as.POSIXct("2024-10-14 12:57:00.000")

walk_4 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(walk_4$X)
mean(walk_4$Y)
mean(walk_4$Z)

start_time <- as.POSIXct("2024-10-14 17:05:00.000")
end_time <- as.POSIXct("2024-10-14 17:10:00.000")

walk_5 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(walk_5$X)
mean(walk_5$Y)
mean(walk_5$Z)

start_time <- as.POSIXct("2024-10-12 11:56:00.000")
end_time <- as.POSIXct("2024-10-12 12:20:00.000")

cycle_1 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(cycle_1$X)
mean(cycle_1$Y)
mean(cycle_1$Z)

start_time <- as.POSIXct("2024-10-12 12:20:00.000")
end_time <- as.POSIXct("2024-10-12 12:40:00.000")

cycle_2 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(cycle_2$X)
mean(cycle_2$Y)
mean(cycle_2$Z)

start_time <- as.POSIXct("2024-10-12 17:12:00.000")
end_time <- as.POSIXct("2024-10-12 17:28:00.000")

cycle_3 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(cycle_3$X)
mean(cycle_3$Y)
mean(cycle_3$Z)

start_time <- as.POSIXct("2024-10-12 17:40:00.000")
end_time <- as.POSIXct("2024-10-12 17:52:00.000")

cycle_4 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(cycle_4$X)
mean(cycle_4$Y)
mean(cycle_4$Z)

start_time <- as.POSIXct("2024-10-12 10:17:00.000")
end_time <- as.POSIXct("2024-10-12 10:42:00.000")

run_1 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(run_1$X)
mean(run_1$Y)
mean(run_1$Z)

start_time <- as.POSIXct("2024-10-12 13:10:00.000")
end_time <- as.POSIXct("2024-10-12 13:45:00.000")

sit_1 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(sit_1$X)
mean(sit_1$Y)
mean(sit_1$Z)

start_time <- as.POSIXct("2024-10-10 08:32:00.000")
end_time <- as.POSIXct("2024-10-10 08:35:00.000")

stairs_1 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(stairs_1$X)
mean(stairs_1$Y)
mean(stairs_1$Z)

start_time <- as.POSIXct("2024-10-10 18:21:00.000")
end_time <- as.POSIXct("2024-10-10 18:38:00.000")

car_1 <- df_1 %>%
  filter(time >= start_time & time <= end_time)

mean(car_1$X)
mean(car_1$Y)
mean(car_1$Z)

```

We will now attempt to more closely analyse one specific period of activity. As an example we take a walking period that is known to be uninterrupted: Thursday 8:22-8:28. Another candidate will be the stairs period.

```{r}
#view(walk_3)
length(stairs_1$X)

spectrum <- fft(walk_3$X)
spectrum_magnitude <- Mod(spectrum)
plot(spectrum_magnitude, type = 'h', main = 'Frequency Spectrum', xlab = 'Frequency', ylab = 'Magnitude')

spectrum <- fft(walk_2$Y)
spectrum_magnitude <- Mod(spectrum)
plot(spectrum_magnitude, type = 'h', main = 'Frequency Spectrum', xlab = 'Frequency', ylab = 'Magnitude')

spectrum <- fft(walk_2$Z)
spectrum_magnitude <- Mod(spectrum)
plot(spectrum_magnitude, type = 'h', main = 'Frequency Spectrum', xlab = 'Frequency', ylab = 'Magnitude')

spectrum <- fft(car_1$X)
spectrum_magnitude <- Mod(spectrum)
plot(spectrum_magnitude, type = 'h', main = 'Frequency Spectrum', xlab = 'Frequency', ylab = 'Magnitude')

```

```{r}
spectrum_magnitude <- Mod(spectrum)
top_20_indices <- order(spectrum_magnitude, decreasing = TRUE)[1:20]
top_20_values <- spectrum_magnitude[top_20_indices]
view(top_20_values)
```

```{r}
walk_1[1:100,] %>% ggplot(aes(y = Y, x = time)) + geom_point() + geom_line(aes(y = mean(walk_1$Y)))

fri_night_1[1:100,] %>% ggplot(aes(y = Z, x = time)) + geom_line()
```

```{r}
acf(sit_1$Z, lag.max = 100)
```

```{r}
temp <- acf(fri_night_1$Z, lag.max = 100)
temp
```


