```{r, message=F, warning=F}
#Data analysis
library(tidyverse)
library(latex2exp)
library(patchwork)
library(scales)
library(RColorBrewer)

#Working with the activity class and data files
library(lubridate)
library(read.gt3x)
library(PhysicalActivity)

#Solving equations
library(nleqslv)
library(pracma)
library(latex2exp)

#Reshaping / data manipulation
library(reshape2)
library(data.table)

##gganimate/creating animations
library(gganimate)
library(glue)
library(shiny)
library(av)
library(magick)
```

## Application to walkEmma

```{r}
#Step 1 + 2
df <- Walk2
folder_name <- "walkEmma"
dir.create(file.path("frames", folder_name), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path("frames", folder_name, "video"), recursive = TRUE, showWarnings = FALSE)
cmd <- paste0("ffmpeg -ss 00:00:00 -t 3334 -i frames/", folder_name, "/", folder_name, ".MTS -q:v 3 -vf \"fps=30,scale=600:340\" frames/", folder_name, "/video/frame_%05d.jpg")
system(cmd)

#Step 3
vid_frames <- length(list.files(paste0("frames/", folder_name, "/video"), pattern = "\\.jpg"))
no_of_hundreds <- 1 + vid_frames %/% 100
for(j in 0:(no_of_hundreds-1)){
  dir.create(file.path("frames", folder_name, paste0("Sideways", j)), recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path("frames", folder_name, paste0("Forward", j)), recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path("frames", folder_name, paste0("Vertical", j)), recursive = TRUE, showWarnings = FALSE)
  }

#Step 4 (but determined with semi-automatic approach)
start_time <-   as.POSIXct("2025-01-20 14:17:55.000")
#Not too great, but good enough for counting steps. Possibly off by about 10 either way?

#Step 5
#Display parameters
fw_bottom <- -Inf
fw_top <- Inf
vert_bottom <- -Inf
vert_top <- Inf
side_bottom <- -Inf
side_top <- Inf
fig_width <- 800
fig_height <- 320
fix_y <- F

#Step partition parameters
wdw_size <- 120
ma_data <- 5 #Maybe split up into two parameters, one for peak/valley and one for analysis
ma_energy <- 5 #Changed from 9. Better?
kernel_func <- ma_gauss 
std_dev <- 1
upright_thresh <- 0.75
abs_acc_thresh <- 0.1 
thresh_abs <- 0.005 
thresh_rel <- 0.25 
min_step_period <- 5
max_step_period <- 40
period_len <- 5 
period_len_double <- 5
period_thresh <- 0.14
double_step_thresh <- 0.21
thresh_direction <- 0.3


#Step 6
dir.create(file.path("frames", folder_name, "Averages"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path("frames", folder_name, "Forward"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path("frames", folder_name, "Vertical"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path("frames", folder_name, "Sideways"), recursive = TRUE, showWarnings = FALSE)

data_walkEmma <- generate_data(folder_name,
                width, 
                start_time, 
                df,
                wdw_size,
                ma_data,
                ma_energy,
                kernel_func,
                std_dev,
                upright_thresh,
                abs_acc_thresh,
                thresh_abs,
                thresh_rel,
                min_step_period,
                max_step_period,
                period_len,
                period_len_double,
                period_thresh,
                double_step_thresh,
                thresh_direction)

steps_info_walkEmma <- df_all_from_mvm_alt_nofilter(data_walkEmma, 200, min_square_difference_vert)

generate_images_avg(steps_info_walkEmma, 0.8, folder_name)
  
generate_images(folder_name,
                         width, 
                         start_time, 
                         fw_bottom,
                         fw_top,
                         vert_bottom,
                         vert_top,
                         side_bottom,
                         side_top,
                         fig_width,
                         fig_height,
                         fix_y,
                         data_walkEmma)

streamvid <- "video"
stream1 <- "Forward"
stream2 <- "Vertical"
stream3 <- "Sideways"

shiny_walkEmma <- generate_server(vid_frames,
                         folder_name,
                         streamvid,
                         stream1,
                         stream2,
                         stream3)

shinyApp(ui = shiny_walkEmma[[1]], server = shiny_walkEmma[[2]])
```

## Example of finding a precise starting time, applied to walkEmma

```{r}
#step 1
raw_df <- Walk2
raw_folder_name <- "walkEmma"
dir.create(file.path("frames", raw_folder_name, "video_raw"), recursive = TRUE, showWarnings = FALSE)

start_vid_raw <- "00:00:25"
length_vid_raw <- "15"
cmd <- paste0(
  "ffmpeg -i frames/", raw_folder_name, "/", raw_folder_name, ".MTS ",
  " -ss ", start_vid_raw, 
  " -t ", length_vid_raw, 
  " -q:v 3 -vf \"fps=30,scale=600:340\" frames/", 
  raw_folder_name, "/video_raw/frame_%05d.jpg"
)
system(cmd)

#Step 2
estimated_start_time_raw <- as.POSIXct("2025-01-20 14:18:20.000")
#The estimated start time of the part of the video you use to calibrate

#Step 3
fw_bottom <- -Inf
fw_top <- Inf
vert_bottom <- -Inf
vert_top <- Inf
side_bottom <- -Inf
side_top <- Inf
fig_width <- 800
fig_height <- 320
fix_y <- F

#Step 4
dir.create(file.path("frames", raw_folder_name, "X"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path("frames", raw_folder_name, "Y"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path("frames", raw_folder_name, "Z"), recursive = TRUE, showWarnings = FALSE)

generate_raw_images(raw_folder_name,
                    width,
                    estimated_start_time_raw,
                    raw_df,
                    fix_y,
                    X_bottom,
                    X_top,
                    Y_bottom,
                    Y_top,
                    Z_bottom,
                    Z_top)

raw_streamvid <- "video_raw"
raw_stream1 <- "X"
raw_stream2 <- "Y"
raw_stream3 <- "Z"

raw_vid_frames <- length(list.files(paste0("frames/", folder_name, "/video_raw"), pattern = "\\.jpg"))

shiny_walkEmma_raw <- generate_server(raw_vid_frames,
                         raw_folder_name,
                         raw_streamvid,
                         raw_stream1,
                         raw_stream2,
                         raw_stream3)

shinyApp(ui = shiny_walkEmma_raw[[1]], server = shiny_walkEmma_raw[[2]])
```

```{r}
frames_difference <- 14
#How many frames the figures on the left are ahead of the video on the right
#If the figures on the left are behind, input a negative number

seconds <- as.numeric(as.POSIXct(start_vid_raw, format="%H:%M:%S")) - 
           as.numeric(as.POSIXct("00:00:00", format="%H:%M:%S"))

estimated_start_time_raw_new <- as.POSIXct(as.numeric(estimated_start_time_raw) - frames_difference/30)
#Can decide to run again with this new estimation of the start of the raw frames

estimated_start_time <- as.POSIXct(as.numeric(estimated_start_time_raw_new) - seconds)
```

## Example of finding an estimated starting time, applied to walkEmma

```{r}
temp <- filter(Walk2, time > as.POSIXct("2025-01-20 14:24:04.000"), time <  as.POSIXct("2025-01-20 14:24:40.000"))
plot(temp$Y, type = 'l')
```
