```{r, message=F, warning=F}
#Data analysis
library(tidyverse)
library(latex2exp)
library(patchwork)
library(scales)
library(RColorBrewer)

#Working with the activity class and data files
library(lubridate)
library(read.gt3x)
library(PhysicalActivity)

#Solving equations
library(nleqslv)
library(pracma)
library(latex2exp)

#Reshaping / data manipulation
library(reshape2)
library(data.table)
library(zeallot)

##gganimate/creating animations
library(gganimate)
library(glue)
library(shiny)
library(av)
library(magick)

#Clustering
library(dbscan)
library(cluster)
library(plotly)
library(htmlwidgets)
library(htmltools)

library(meanShiftR)
library(MASS)
library(mclust)
```

## Short_files analysis with k-shift

```{r}
D <- short_distance_data_walk3_cor[[1]]
coords <- cmdscale(as.dist(D), k = 2)
coords_df <- as.data.frame(coords)
colnames(coords_df) <- c("Dim1", "Dim2")

dens <- kde2d(coords_df$Dim1, coords_df$Dim2, n = 100) 

ggplot(coords_df, aes(x = Dim1, y = Dim2)) +
  geom_tile(data = as.data.frame(expand.grid(x = dens$x, y = dens$y)),
            aes(x = x, y = y, fill = as.vector(dens$z)), inherit.aes = FALSE, alpha = 0.6) +
  scale_fill_viridis_c() +
  geom_point(color = "black", size = 1.5) +
  labs(x = "Dimension 1", y = "Dimension 2", fill = "Density") +
  theme_minimal()
```

```{r}
gmm <- Mclust(coords_df)

centers <- as.data.frame(gmm$parameters$mean)
colnames(centers) <- c("Dim1", "Dim2")

ggplot(coords_df, aes(x = Dim1, y = Dim2)) +
  geom_tile(data = as.data.frame(expand.grid(x = dens$x, y = dens$y)),
            aes(x = x, y = y, fill = as.vector(dens$z)), inherit.aes = FALSE, alpha = 0.6) +
  scale_fill_viridis_c() +
  geom_point(color = "black", size = 1.5) +
  geom_point(data = centers, aes(x = Dim1, y = Dim2), color = "red", size = 4, shape = 4) +
  labs(title = "2D Projection with GMM Centers and Density",
       x = "Dimension 1", y = "Dimension 2", fill = "Density") +
  theme_minimal()
```