### Importing libraries

```{r, message=F, warning=F}
library(tidyverse)
```

First a general test on some synthetic data

```{r}
temp_data <- c(1,2,1,3,5,1,4,1,2,3,1,4,1,5,71,64,42,41,53,34,43,52,42,53,41,43,48,27,32,45,18,2,1,4,1,2,3,1,4,1,5,1,2,3,1,2,3,2,3,5,1,2,1,2,1,3,1)

temp <- data.frame(raw = temp_data, ma = ma(temp_data, n = 7), ma_left = ma_left(temp_data, n = 3), ma_right = ma_right(temp_data, n = 4)) #This only works for start as we take 3,4. In addition, we need to consider the left value a column earlier


temp_part <- activity_partition_to_df(temp, 2, 7, 1, 8)

temp_part_trim <- trim_activity_partition_3(temp_part, 7, 1, 5)

temp_part_trim <- trim_activity_partition_4(temp_part, 7, 1, 5)
view(temp_part_trim)
``` 

Now some more synthetic testing 

```{r}
temp_data <- c(1,2,5,2,3,4,1,4,10,14,12,2,1,3,1,4,1,2,4,1)
n = 5
n_skip = (n-1)/2

temp <- data.frame(raw = temp_data, ma = ma(temp_data, n = n), ma_left = ma_left(temp_data, n = n_skip), ma_right = ma_right(temp_data, n = n_skip+1))
temp_part <- activity_partition_to_df(temp, 2, n, 1, 5)

temp_part_trim <- trim_activity_partition_3(temp_part, n, 1, 5)
temp_part_trim <- trim_activity_partition_4(temp_part, n, 1, 5)
view(temp_part_trim)


```

